In [1]:
import pandas as pd
import numpy as np

# READ THE CSV INTO DATAFRAME

df = pd.read_csv('Syngenta/Syngenta_2017/Experiment_dataset.csv')

np_ar = np.asarray(df)
# df2 = pd.read_csv('Syngenta/Syngenta_2017/Region_dataset.csv')

In [ ]:
print(df.columns)
print(df.Temperature.describe())

In [2]:
# CURRENTLY NECESSARY IF: USING 174 ADDITIONAL VARIETY COLUMNS METHOD

# THIS IS A DIFFERENT APPROACH TO THE ABOVE FOUR CELLS, WHERE WE HAVE 174 ADDITIONAL FEATURE COLUMNS
# EACH WITH A 0 (IF IT IS NOT OF THAT VARIETY) OR A 1 (IF IT IS OF THAT VARIETY)

# print(df)
variety_dummies = pd.get_dummies(df.Variety)
# print(dummies)
df = pd.concat([df, variety_dummies], axis=1)


In [41]:
print(variety_dummies.sum().describe())
print(np.sort(variety_dummies.sum()))
for idx, cl in enumerate(variety_dummies.sum()):
    print(variety_dummies.columns[idx], cl)

count     174.000000
mean      471.471264
std       642.755886
min        38.000000
25%       111.250000
50%       215.000000
75%       560.000000
max      3849.000000
dtype: float64
[  38   40   45   46   56   57   66   70   71   71   73   75   76   76
   76   77   80   80   81   81   82   82   87   88   89   93   93   94
   94   95   96   96   96   97   98   98  103  104  106  106  106  107
  110  111  112  113  114  114  115  115  118  124  125  125  127  131
  131  132  134  135  145  145  146  150  150  152  154  154  159  161
  163  163  167  170  179  179  180  180  186  186  187  188  192  193
  198  211  213  217  218  218  220  222  223  230  231  237  245  249
  258  271  273  279  281  283  283  291  299  303  304  304  310  311
  312  319  319  322  325  325  330  337  345  345  369  389  410  439
  442  464  543  545  565  576  581  596  604  611  622  628  673  679
  723  729  738  788  793  819  834  835  872 1004 1040 1095 1114 1133
 1212 1226 1236 1246 1269 1371 1445 

In [14]:
df.columns.str.match('V')

array([False, False,  True, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,

In [ ]:
# GOAL OF THIS MODULE:
# Encode the planting date as a season

# remove the dates that are "."
df = df[~df['Planting date'].str.match("\.")]
plant_date = df['Planting date'].apply(lambda dt: pd.to_datetime(dt))
plant_date = plant_date.rename("Season")
plant_date = pd.to_datetime(plant_date)
plant_date = plant_date.apply(lambda dt: (dt.month%12 + 3)//3)
# df['Plant date'] = pd.to_datetime(df['Plant date'])
df = pd.concat([df, plant_date], axis=1)

# plant_date = pd.to_datetime(df['Planting date'], infer_datetime_format=True)
# df = df['Planting date'].apply(lambda dt: (dt.month%12 + 3)//3)
# pd.get_dummies(df['Planting date'])


In [ ]:
df['Season']

In [ ]:
print(df.columns)
print(df.isnull().sum())

In [ ]:
# LATITUDE AND LONGITUDE CLUSTERING INTO FEATURES

from sklearn.cluster import KMeans

latlong = df.loc[:, ['Latitude', 'Longitude']]

kmeans = KMeans(n_clusters=4, random_state=0).fit(latlong)
kmeans.labels_.shape
lat_long_dummies = pd.get_dummies(kmeans.labels_).rename(index=int, columns={0: "Loc Clust 0", 1: "Loc Clust 1", 2: "Loc Clust 2", 3: "Loc Clust 3"})
df = pd.concat([df, lat_long_dummies], axis = 1)

In [20]:
np.asarray(df.iloc[:, df.columns.str.match('V\d\d\d\d\d\d')].columns)

array(['V000016', 'V000017', 'V000018', 'V000023', 'V000024', 'V000025',
       'V000030', 'V000032', 'V000034', 'V000036', 'V000039', 'V000047',
       'V000050', 'V000051', 'V000058', 'V000060', 'V000062', 'V000067',
       'V000070', 'V000071', 'V000075', 'V000078', 'V000079', 'V000080',
       'V000081', 'V000082', 'V000092', 'V000096', 'V000098', 'V000110',
       'V000115', 'V000122', 'V000123', 'V000124', 'V000125', 'V000134',
       'V000147', 'V000157', 'V000172', 'V000721', 'V031243', 'V051214',
       'V103132', 'V103136', 'V103139', 'V103142', 'V103150', 'V103155',
       'V103156', 'V103159', 'V103163', 'V103173', 'V103193', 'V103198',
       'V103259', 'V103266', 'V103273', 'V103277', 'V103281', 'V103286',
       'V103293', 'V103302', 'V103303', 'V103308', 'V103332', 'V103425',
       'V103466', 'V103620', 'V103624', 'V103866', 'V103970', 'V104000',
       'V110768', 'V110890', 'V110923', 'V111237', 'V111336', 'V113396',
       'V113424', 'V113476', 'V114530', 'V114541', 

In [ ]:
#THIS IS A VISUALIZATION FOR LATITUDE AND LONGITUDE CLUSTERING

cent = kmeans.cluster_centers_
clust_labels = kmeans.labels_
means = pd.DataFrame(clust_labels)

import matplotlib.pyplot as plt
fig = plt.figure()
ax = fig.add_subplot(111)
scatter = ax.scatter(df['Latitude'],df['Longitude'],
                     c=means[0], s=50)
ax.set_title('K-Means Clustering')
ax.set_xlabel('Latitude')
ax.set_ylabel('Longitude')
plt.colorbar(scatter)

In [ ]:
#REMOVE ANY NAN VALUES

print(df.columns)
df = df[~df.Silt.isnull()]
df = df[~df['Loc Clust 1'].isnull()]

In [ ]:
from sklearn import preprocessing
lb = preprocessing.LabelBinarizer()
binarized = lb.fit(df.Variety)
print(binarized)
df.Variety = pd.Series(binarized.transform(df.Variety))
print(binarized.transform(df.Variety).reshape(1,-1))

In [ ]:
for col in df.columns:
    print(col, type(df[col][0]))

In [26]:
# DROP ALL THE CELLS THAT ARE NOT USABLE SUCH AS THE ONES THAT ARE STRINGS OR DATES

# set if want to drop some columns specifically
should_drop = 0
columns_to_drop = ['Experiment', 'Location',
                   'Check Yield', 'Yield difference', 'Latitude',
                   'Longitude', 'Variety', 'PI', 'Planting date']

# set if want to keep some columns specifically
should_keep = 1
# columns_to_keep = ['Loc Clust 0', 'Loc Clust 1', 'Loc Clust 2', 'Loc Clust 3']
columns_to_keep_top = ['Silt', 'Precipitation', 'Temperature']
columns_VARIETIES_ONLY = np.asarray(df.iloc[:, df.columns.str.match('V\d\d\d\d\d\d')].columns)

#set the below variable to whatever columns you want to keep
columns_to_keep = columns_VARIETIES_ONLY

MUST_HAVE_COLUMNS = ['Yield']
# print(columns_to_keep)

df = df.drop(columns_to_drop, axis=1) if should_drop else df
df = df.loc[:, np.concatenate((columns_to_keep, MUST_HAVE_COLUMNS))] if should_keep else df
df['YieldBucket'] = pd.Series(pd.qcut(df.Yield, q=3, labels=["high", "medium", "low"]))
print(df.columns)

Index(['V000016', 'V000017', 'V000018', 'V000023', 'V000024', 'V000025',
       'V000030', 'V000032', 'V000034', 'V000036',
       ...
       'V156642', 'V156763', 'V156774', 'V156783', 'V156786', 'V156797',
       'V156806', 'V156807', 'Yield', 'YieldBucket'],
      dtype='object', length=176)


In [ ]:
print(pd.get_dummies(df.YieldBucket).sum())

In [ ]:
# LET US ALSO MAKE SURE THERE ARE NO NAN IN THE DATA
print("We expect to be %s nan values and there actually are %s nan values\n" % (0, np.sum(df.isnull().sum())))
print(df.isnull().sum())
# AFTER COLUMNS, MAKE SURE NO SKETCHY ONES
for col in df.columns:
    print(col, type(df[col][0]))    

In [27]:
# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT
# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT
# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT
# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT# TRAIN AND TEST SPLIT

X = df.drop(['Yield', 'YieldBucket'], axis=1)

print(X.columns)

y = df.Yield

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.05, train_size = 0.1, random_state = 42)

Index(['V000016', 'V000017', 'V000018', 'V000023', 'V000024', 'V000025',
       'V000030', 'V000032', 'V000034', 'V000036',
       ...
       'V156565', 'V156574', 'V156642', 'V156763', 'V156774', 'V156783',
       'V156786', 'V156797', 'V156806', 'V156807'],
      dtype='object', length=174)


In [ ]:
print("X_train shape:", X_train.shape, "\ny_train shape:", y_train.shape)

In [28]:
# This function will evaluate the errors based on RMSE (from the challenge spec)
# also will evaluate based on average error

from sklearn.metrics import mean_squared_error
def evaluate_errors(prediction, actual):
    print("RMSE Error: ", np.sqrt(mean_squared_error(prediction, actual)))
    avg_error_vector = np.absolute(((preds - y_test) / y_test) * 100)
#     print("Average Error: ", np.mean(avg_error_vector))
    print("Average Error details:\n", avg_error_vector.describe())

In [29]:
from sklearn.ensemble import RandomForestRegressor
regr = RandomForestRegressor(n_estimators=10, max_depth=20, random_state=0, verbose=1)
regr.fit(X_train, y_train)
preds = regr.predict(X_test)

evaluate_errors(preds, y_test)

RMSE Error:  11.019433343628817
Average Error details:
 count    4102.000000
mean       16.064871
std        16.584654
min         0.005440
25%         5.662837
50%        12.117249
75%        20.806759
max       249.859833
Name: Yield, dtype: float64


[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.5s finished
[Parallel(n_jobs=1)]: Done  10 out of  10 | elapsed:    0.0s finished


In [ ]:
pd.get_dummies(df['Plant date']).sum()

In [30]:
# GET OUTPUT OF FEATURE IMPORTANCE

feature_importances = regr.feature_importances_
feature_importances = pd.Series(feature_importances)
feature_importance_df = pd.DataFrame({'feature': X_train.columns,'feature_importance': feature_importances})
feature_importance_df = feature_importance_df.sort_values(by=['feature_importance'])
for index, row in feature_importance_df.iterrows():
    print(row['feature'], 'has importance: ', row['feature_importance'])


V000016 has importance:  0.0
V136868 has importance:  0.0
V137136 has importance:  0.0
V137147 has importance:  0.0
V137160 has importance:  0.0
V137237 has importance:  0.0
V137289 has importance:  0.0
V139094 has importance:  0.0
V131778 has importance:  0.0
V139548 has importance:  0.0
V140784 has importance:  0.0
V150844 has importance:  0.0
V150847 has importance:  0.0
V150853 has importance:  0.0
V150974 has importance:  0.0
V151036 has importance:  0.0
V151236 has importance:  0.0
V140091 has importance:  0.0
V151273 has importance:  0.0
V131675 has importance:  0.0
V124343 has importance:  0.0
V114541 has importance:  0.0
V114545 has importance:  0.0
V114553 has importance:  0.0
V114564 has importance:  0.0
V114944 has importance:  0.0
V114951 has importance:  0.0
V120047 has importance:  0.0
V130305 has importance:  0.0
V120410 has importance:  0.0
V120810 has importance:  0.0
V120912 has importance:  0.0
V120999 has importance:  0.0
V121015 has importance:  0.0
V121097 has im

In [ ]:
# THIS WILL ONLY WORK WITH THE BUCKET METHOD

from sklearn.ensemble import RandomForestClassifier
regr = RandomForestClassifier(n_estimators=10, max_depth=20, random_state=0, verbose=1)
regr.fit(X_train, y_train)
preds = regr.predict(X_test)

from sklearn.metrics import accuracy_score

print(accuracy_score(y_test, preds))

In [ ]:
import numpy as np
from sklearn import linear_model
from sklearn import svm
from sklearn.metrics import accuracy_score
from sklearn.neural_network import MLPRegressor

from sklearn.feature_selection import RFECV

classifiers = [
    svm.SVR(),
    MLPRegressor(solver='lbfgs', alpha=1e-5,
                     hidden_layer_sizes=(5, 2), random_state=1),
    linear_model.SGDRegressor(),
    linear_model.BayesianRidge(),
    linear_model.LassoLars(),
#     linear_model.ARDRegression(),
#     linear_model.ARDRegression(),
    linear_model.PassiveAggressiveRegressor(),
    linear_model.TheilSenRegressor(),
    linear_model.LinearRegression()]




# estimator = svm.SVR(kernel="linear")

# selector = RFECV(estimator, step=1, cv=5, verbose=1)
# selector = selector.fit(X_train, y_train)
# selector.support_ 
# # array([ True,  True,  True,  True,  True,
# #         False, False, False, False, False], dtype=bool)
# selector.ranking_
# # array([1, 1, 1, 1, 1, 6, 4, 3, 2, 5])


#     print(np.sum(preds - y_test))
#     print(clf.predict(X_test),'\n')
#     print(y_test)
#     print('accuracy score:', accuracy_score(y_test, clf.predict(X_test)), '\n')


In [ ]:
for item in classifiers:
    print(item)
    clf = item
    clf.fit(X_train, y_train)
    preds = clf.predict(X_test)
    errors = mean_squared_error(preds, y_test)
#     errors = np.absolute(((preds - y_test) / y_test) * 100)
#     print(errors)
    print(errors)
#     print(errors.describe())

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_moons, make_circles, make_classification
from sklearn.neural_network import MLPClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, AdaBoostClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

classifiers = [
#     KNeighborsClassifier(3),
#     SVC(kernel="linear", C=0.025),
    SVC(gamma=2, C=1),
#     GaussianProcessClassifier(1.0 * RBF(1.0)),
#     DecisionTreeClassifier(max_depth=5),
    RandomForestClassifier(max_depth=5, n_estimators=10, max_features=1),
    MLPClassifier(alpha=1),
    AdaBoostClassifier(),
    GaussianNB(),
    QuadraticDiscriminantAnalysis()]
from sklearn.metrics import accuracy_score
for item in classifiers:
    print(item)
    clf = item
    clf.fit(scale(X_train), y_train)
    preds = clf.predict(scale(X_test))
    print(accuracy_score(y_test, preds))
#     errors = np.absolute(((preds - y_test) / y_test) * 100)
#     print(errors)
#     print(np.mean(errors))